Allow resolving mixed builds in eager resolve mode
eclipse-tycho/tycho pull request #2343
Opened 2023-04-10 12:38 UTC by lppedd

This reuse the same concept used in `TychoReactorReader`, more or less.

`InstallableUnitGenerator` takes for granted a JAR file has been built already for a project that is inside the same reactor.  
This is not always the case.

2023-04-10 12:40 UTC, lppedd commented
This is related to #2341.

2023-04-10 12:40 UTC, laeubi requested changes
As already said, this is nothing Tycho should/would support.

2023-04-10 12:43 UTC, laeubi commented
> @laeubi there is nothing related to IDEs here. This simply allows resolving non-Tycho packagings without requiring them to have been built already.

If they are not build, Tycho can't use them because there is no generic way to know what packages they export, what bundle or version they will provide and so on.

2023-04-10 12:48 UTC, lppedd commented
@laeubi obviously that is not the typical use-case.

IntelliJ IDEA injects a custom `WorkspaceReader` that returns a project's base directory in case that project doesn't have an artifact associated already. This demo PR shows that by letting Tycho work with a directory instead of a JAR file only, the entire flow works smoothly.

In any other context where there are no custom `WorkspaceReader`s injected, Tycho will work as before.

2023-04-10 13:54 UTC, laeubi commented
A base directory is not enough. The general contract for a mixed build is that the project produces a jarfile and this jar file is a bundle, everything else is invalid and not supported.

So please provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue with a plain `mvn clean verify`, and then we probably can change things showing that this use-case now works.

2023-04-10 14:29 UTC, lppedd commented
@laeubi the problem here is that you see Tycho only from the build perspective. Not all tools that use Maven will use it to build.

Some tools only need to configure themselves based on how Maven generate its model.
In this specific case what happens is the Maven model will register a "mixed" jar-packaged project as a dependency of another tycho-packaged project, that's it. No build will ever occur.

2023-04-10 15:35 UTC, laeubi commented
As said Tycho can't take the burden of other tools, if they need special treatment it must be handled there.

If no build ever occurs, the default Tycho mode will be enough and will never give any errors. Eager resolve is only for special cases where the Targetplatform is known in advance and one needs references to reactor projects via transitive dependencies and any other use-case it not supported, especially if it is not possible to write an integration test for this as this is completely internal behavior of Tycho and will change anytime in any way.

> This change allows the Mavel model configuration to finish without generating errors

This seems very unlikely by the provided error you see, that says you depend on another module providing a bundle but Tycho can't know this before the bundle is build and therefore would be never satisfiable.

If you want something similar to what was done before (resolve as much dependencies as currently possible), this can be done by an ow extension (possibly reusing Tycho internal API), but this is not what Tycho resolving process does.

2023-04-10 15:39 UTC, laeubi commented on p2-maven-plugin/src/main/java/org/eclipse/tycho/p2maven/InstallableUnitGenerator.java
> +						final File manifestFile = new File(file, "META-INF/MANIFEST.MF");
If you want such behavior you should simply use the `eclipse-plugin` / `eclipse-feature` packaging for that project.

2023-04-10 15:42 UTC, laeubi commented on tycho-core/src/main/java/org/eclipse/tycho/core/TargetPlatformConfiguration.java
> +            return PomDependencies.consider;
This is an incompatible change, please the the documentation, consider is only the default for eager resolve is not configured.

2023-04-10 15:43 UTC, laeubi commented on tycho-core/src/main/java/org/eclipse/tycho/p2resolver/P2ResolverImpl.java
> +                data.setAdditionalUnitStore(p2ResolverFactoryImpl.getPomUnits().createPomQueryable(project));
This is only valid in lazy mode, because in eager mode all dependencies are already resolved beforehand and can't be read from the pom (again).

2023-04-10 15:55 UTC, lppedd commented
I'll address points here.

> if they need special treatment it must be handled there

There is no way to handle mostly anything outside of Tycho as it is so "self contained" that everybody would have to replicate what Tycho does, which makes no sense.

> this can be done by an ow extension (possibly reusing Tycho internal API)

Cannot be done because of the very changes I had to make here. See `PomDependencies.ignore` > `PomDependencies.consider`.
This is an implementation detail that would be impossible to change externally, and would conflict in the use of `tycho-spi` definitions such as `TychoResolver` in a custom extension.

> If you want such behavior you should simply use the eclipse-plugin / eclipse-feature packaging for that project

Might be true, but a POM-specified dependency should be registered in the model without throwing errors if no build is occurring.

See https://github.com/openjdk/jmc/blob/91329f1b8d9896d5160e22262f06385bf43e960b/application/pom.xml#L151-L155 for the dependency declaration related to the error shown above.

> This seems very unlikely by the provided error you see

I've tested the changes and everything is imported correctly. Obviously tested on JMC and other internal projects.

> consider is only the default for eager resolve is not configured

That change is needed otherwise `PomInstallableUnitStore` will never return a useful query result.
```
if (considerPomDependencies == PomDependencies.ignore) {
    return EMPTY_RESULT;
}
```

2023-04-10 16:51 UTC, lppedd commented
> Also as said, you don't want a "Resolver"

I'm not entirely sure about this. The matter is I need the resolution process against p2 repositories too, I need all the stack. I don't need only inter-workspace resolution. A `GraphBuilder` only handles connections between reactor projects.

> if you want eager resolve of pom dependencies use PomDependencies = consider or PomDependencies = wrap in your target platform

This actually helped, thanks. As this is done through IDE code, I had to add a configurable system property in this style
```
String value = getStringValue(configuration.getChild(POM_DEPENDENCIES), session, "tycho.target.pomDependencies", null);
```
Which is then set before execution
```
@Override
public void customizeUserProperties(
  final Project project,
  final MavenProject mavenProject,
  final Properties properties
) {
  properties.setProperty("tycho.target.eager", "true");
  properties.setProperty("tycho.target.pomDependencies", "consider");
}
```

The good side is I have reverted what you mentioned as a breaking change in `TargetPlatformConfiguration#getPomDependencies`.
Keeping the removal of `if (!configuration.isRequireEagerResolve()) { ... }` in `P2ResolverImpl` seems to be required still tho. The import fails if I reinstate the condition.

> because it won't work if no Manifest is there

Well yes, there is a trade-off to be made, since it is impossible to handle all the cases.

> As said you should provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test)

It's impossible to provide an integration test as the import process is handled through Maven Embedder in the IDE context.

2023-05-18 04:19 UTC, laeubi commented
@lppedd with this PR https://github.com/eclipse-tycho/tycho/pull/2418 Tycho now can detect `bnd-process` and generates a preliminary manifest if eager resolution is requested (you still need to enable to consider pom dependencies just in case), probably you want to try that out if it helps with your issue, but depending on your exact configuration it might need some enhancements (e.g. if you use bnd:jar or similar).

2023-05-18 04:20 UTC, closed without merging