assemble-repository: Prevent sources from being included inadvertently
eclipse-tycho/tycho pull request #3635
Opened 2024-03-12 17:12 UTC by sratz

In the presence of products, P2 adds a virtual 'tooling.source.default' IU which optionally depends on all sources.

If these sources are avaialble in the target platform, this would cause them to be picked up even if assemble-repository was configured with <includeAllSources>false</includeAllSources>.

This scenario has become much more likely with recent changes to P2 [1].

To prevent this, we actively prevent this from happening by ignoring the requirements of the 'tooling.source.default' IU unless includeAllSources is explicitly enabled.

These would be picked up even if If however, assemble-repository is

Fixes #3522.

[1] https://github.com/eclipse-equinox/p2/pull/446

2024-03-14 07:54 UTC, laeubi requested changes
It goes in the right direction but basically I would 

1. check here if this is a requirement for a source bundle
2. Construct a context IU with `org.eclipse.update.install.sources=true/false`
3. then check if they match in `isApplicable(IInstallableUnit iu, IRequirement req)`

that way the requirements will just be filtered out.

2024-03-14 07:54 UTC, laeubi commented on tycho-core/src/main/java/org/eclipse/tycho/p2tools/TychoMirrorApplication.java
> +            private static final String TOOLING_SOURCE_IU_ID = PublisherHelper.createDefaultConfigUnitId("source",
I'm not sure this is the correct approach also the test failuresindicate that.

2024-03-14 07:54 UTC, laeubi commented on tycho-core/src/main/java/org/eclipse/tycho/p2tools/TychoMirrorApplication.java
>                  if ((includeRequiredBundles || includeRequiredFeatures) && QueryUtil.isGroup(iu)
I think this is actually the place where you want to filter things, this test if a requirement for a IU is applicable and you don't want the new requirement to be considered.

2024-03-15 14:10 UTC, sratz commented
> 1\. check here if this is a requirement for a source bundle
> 2\. Construct a context IU with `org.eclipse.update.install.sources=true/false`

I'm not sure I understand this part.
Where is 'here'?
What's a 'context IU'?
Also, as the problem is not the `org.eclipse.update.install.sources`, but the fact that a published product contains a `tooling.source.default` IU which optionally depends on all sources.

> 3\. then check if they match in `isApplicable(IInstallableUnit iu, IRequirement req)`

I think this is the important aspect. We don't want to filter
`tooling.source.default` itself in `isApplicable(IInstallableUnit iuIRequirement req)`
but only filter
`tooling.source.default`'s dependencies in `isApplicable(IInstallableUnit iuIRequirement req)`.

I have moved the condition to `isApplicable(IInstallableUnit iuIRequirement req)`, let's see what the test suite says.

2024-03-15 14:17 UTC, laeubi commented
I must confess I'm not sure `tooling.source.default` is really the problem. This has not changed recently but what has changed is that each bundle now has the `org.eclipse.update.install.sources` requirement.

2024-03-15 14:20 UTC, sratz commented
> I must confess I'm not sure `tooling.source.default` is really the problem. This has not changed recently but what has changed is that each bundle now has the `org.eclipse.update.install.sources` requirement.

It has not changed, but before `org.eclipse.update.install.sources` was introduced those sources weren't part of the target platform.

Now they are, and the effect of `tooling.source.default` now pulls them in.

2024-03-15 14:23 UTC, sratz commented
An alternative to the current proposal of looking at `tooling.source.default` could be to provide a filtered view on the project's target platform with `org.eclipse.update.install.source=true` IUs excluded. Then, using that filtered target platform to initiate the mirroring. But I am not sure I know how to do that.

2024-03-18 07:56 UTC, laeubi commented
As said this are not _IUs_ but _Requirements_ ... You can create a so called "context IU" from a map of properties with `InstallableUnit.contextIU(context)` in your case maybe `InstallableUnit.contextIU(Map.of(org.eclipse.update.install.source, includeAllSources))`, if you have that you can use 

```
IMatchExpression<IInstallableUnit> filter = req.getFilter();
return filter == null || filter.isMatch(contextIU);
```

for example to check if a requirement is matching that context IU.

2024-03-18 08:48 UTC, sratz commented
> As said this are not _IUs_ but _Requirements_ ... You can create a so called "context IU" from a map of properties with `InstallableUnit.contextIU(context)` in your case maybe `InstallableUnit.contextIU(Map.of(org.eclipse.update.install.source, true))`, if you have that you can use
> 
> ```
> IMatchExpression<IInstallableUnit> filter = req.getFilter();
> booelan matches =  filter != null && filter.isMatch(contextIU);
> ```
> 
> for example to check if a requirement is matching that context IU and if yes return false from is applicable if includeAllSources is false.

I tried this:

```java
            private static final IInstallableUnit SOURCEC_CONTEXT = InstallableUnit
                    .contextIU(Map.of("org.eclipse.update.install.source", "true"));

            @Override
            protected boolean isApplicable(IInstallableUnit iu, IRequirement req) {
                if (!includeAllSource) {
                    IMatchExpression<IInstallableUnit> filter = req.getFilter();
                    if (filter != null) {
                        if (filter.isMatch(SOURCEC_CONTEXT)) {
                            // When dealing with a repository that contains published products, these products
                            // always include a dependency to 'tooling.source.default', which picks up all sources.
                            // And since https://github.com/eclipse-equinox/p2/pull/446 the target platform contains
                            // all the sources. They would be picked up unless we prevent this here.
                            // See https://github.com/eclipse-tycho/tycho/issues/3522
                            return false;
                        }
                    }
                }
```

but it does not work.

As outlined in the issue, the problematic IU is `tooling.source.default` which has an `IRequirement` on all source providers:
```java
		// Create a required capability on source providers
		IRequirement[] reqs = new IRequirement[] {MetadataFactory.createRequirement(NAMESPACE_ECLIPSE_TYPE, TYPE_ECLIPSE_SOURCE, VersionRange.emptyRange, null, true, true, false)};
		cu.setHost(reqs);
		Map<String, String> touchpointData = new HashMap<>();
```

https://github.com/eclipse-equinox/p2/blob/e0ce87e039a001c4aafcbb2dba6ca33455933097/bundles/org.eclipse.equinox.p2.publisher/src/org/eclipse/equinox/spi/p2/publisher/PublisherHelper.java#L169-L189


This requirement does not have any filter so the code above will not be able to filter anything here based on the context IU.

2024-03-18 09:19 UTC, laeubi commented
@merks yna you give a hint about the `tooling.source.default` IU?

2024-03-18 09:53 UTC, merks commented
One thing that might generally be helpful here is that this is an optional **non-greedy** requirement:
```
<unit id='tooling.source.default' version='1.0.0' singleton='false'>
  <hostRequirements size='1'>
    <required namespace='org.eclipse.equinox.p2.eclipse.type' name='source' range='0.0.0' optional='true' multiple='true' greedy='false'/>
  </hostRequirements>
  <properties size='1'>
    <property name='org.eclipse.equinox.p2.type.fragment' value='true'/>
  </properties>
  <provides size='2'>
    <provided namespace='org.eclipse.equinox.p2.iu' name='tooling.source.default' version='1.0.0'/>
    <provided namespace='org.eclipse.equinox.p2.flavor' name='tooling' version='1.0.0'/>
  </provides>
  <requires size='1'>
    <required namespace='org.eclipse.equinox.p2.eclipse.type' name='source' range='0.0.0' optional='true' multiple='true' greedy='false'/>
  </requires>
...
</unit>
```
As far as I understand it, at installation time, an optional non-greedy requirement **will not be installed even when it's available**, i.e., there must be some other non-optional requirements (in which case the required things must be available), or optional greedy requirement (in which case it's installed when available and quietly ignored when not).  

Of course the context here is mirroring and not installing.  I think in the filtering context here that generally it should be possible to ignore all optional non-greedy requirements.  I'm not sure if that should involve yet another configuration option...

2024-03-18 09:55 UTC, laeubi commented
As far as I know "inlcudeAllRequirements" makes everything greedy....

2024-03-18 10:44 UTC, sratz commented
Yes, we have `includeAllDependencies` and `includeAllSources`.

I think the intuitive expectation is that `includeAllDependencies` does not also imply `includeAllSources`.

And previously this expectation was (usually) met, because the sources typically weren't visible via the target platform in these kind of product-containing repository definitions.

So the current proposal of this PR basically ensures that this expectation is met deterministically.

2024-03-18 11:05 UTC, sratz commented
Instead of looking at the IU's name `tooling.source.default`, we could also just look at the `IRequirement` and do this:

```java
                if (!includeAllSource && req.getMin() == 0 && !req.isGreedy()
                        && (PublisherHelper.NAMESPACE_ECLIPSE_TYPE
                                .equals(RequiredCapability.extractNamespace(req.getMatches()))
                                && PublisherHelper.TYPE_ECLIPSE_SOURCE
                                        .equals(RequiredCapability.extractName(req.getMatches())))) {
                    return false;
                }
```

WDYT?

2024-03-18 11:29 UTC, merks commented
That's exactly what I was trying just now:

![image](https://github.com/eclipse-tycho/tycho/assets/208716/6b68ea57-4f05-4f42-869b-aaabdea5ebe8)

I was just making sure the tests still pass but was having problems with the 4.31 repository not loading for some unknown reason.

2024-03-18 11:30 UTC, merks commented
@sratz I suggest you make the change (yes, the test still passes) since I'm a bit incompetent at updating someone else's PR.

2024-03-18 11:31 UTC, sratz commented
> I was just making sure the tests still pass but was having problems with the 4.31 repository not loading for some unknown reason.

had the same, clearing`~.m2/cache` helped.

2024-03-18 11:34 UTC, merks commented
@sratz 

FYI, this test fails for me locally as well:

![image](https://github.com/eclipse-tycho/tycho/assets/208716/bbc6b836-0ac6-4463-b432-f926b53444c0)

So I'm looking at that...

2024-03-18 11:52 UTC, merks commented
@sratz 

The test failure is unrelated and is already fixed in master:

https://github.com/eclipse-tycho/tycho/blob/d6366adf73b9028fb192a550e4bef2950700791a/tycho-core/src/test/java/org/eclipse/tycho/p2resolver/P2ResolverTest.java#L225-L226

The problem is that the test uses a moving target repository so the actual content can and apparently does change:

https://github.com/eclipse-tycho/tycho/blob/d6366adf73b9028fb192a550e4bef2950700791a/tycho-core/src/test/java/org/eclipse/tycho/p2resolver/P2ResolverTest.java#L75

Please ensure that you rebase your change on master.

2024-03-18 14:08 UTC, laeubi approved these changes
Looks good and is backed by test so I think its ready to go.

2024-03-18 14:08 UTC, merged

2024-03-18 14:12 UTC, merks commented
And a back port too.  That's great!  Thanks!!

2024-03-18 14:17 UTC, laeubi commented
@sratz many thanks for the fix, as you already have contributed to Tycho for a while I'd like to ask if you want to become a committer I just would need your email address of the eclipse account and can prepare the vote then!

2024-03-20 09:45 UTC, sratz commented
> @sratz many thanks for the fix, as you already have contributed to Tycho for a while I'd like to ask if you want to become a committer I just would need your email address of the eclipse account and can prepare the vote then!

Thanks for the offer! I pinged you via email.